export interface QuestionItem {
  id: string;
  number?: number | string;
  category: 'sinonimos' | 'antonimos' | 'polisemia' | 'monosemia' | 'campo_semantico' | 'familia_lexica' | 'contexto' | 'figurado' | 'texto' | 'intruso' | 'clasificacion';
  categoryLabelEs: string;
  categoryLabelHy: string;
  // Spanish question / prompt
  promptEs: string;
  // Armenian translation of question / prompt (revealed on click)
  promptHy: string;
  // Optional extra context or sentences
  contextEs?: string;
  contextHy?: string;
  // Type: 'choice' (multiple choice), 'open' (open answer/fill in), 'classify'
  type: 'choice' | 'open' | 'intruso' | 'classify';
  options?: {
    id: string;
    textEs: string;
    textHy?: string;
  }[];
  // Correct answer display
  correctAnswerEs: string;
  correctAnswerHy: string;
  // Detailed explanation
  explanationEs?: string;
  explanationHy?: string;
  // Expected option ID if multiple choice
  correctOptionId?: string;
}

export interface ExerciseSection {
  id: string;
  titleEs: string;
  titleHy: string;
  subtitleEs?: string;
  subtitleHy?: string;
  noteEs?: string;
  noteHy?: string;
  textEs?: string;
  textHy?: string;
  questions: QuestionItem[];
}

export interface PrincipalRule {
  id: string;
  conceptEs: string;
  conceptHy: string;
  defEs: string;
  defHy: string;
  exampleEs: string;
  exampleHy: string;
  quickTipEs: string;
  quickTipHy: string;
}

export const LO_PRINCIPAL_RULES: PrincipalRule[] = [
  {
    id: 'monosemia',
    conceptEs: 'Monosemia',
    conceptHy: 'Մենիմաստություն',
    defEs: 'Una palabra tiene un solo significado.',
    defHy: 'Բառը ունի մեկ հիմնական իմաստ։',
    exampleEs: 'termómetro (instrumento para medir la temperatura)',
    exampleHy: 'termómetro (ջերմաչափ — ունի մեկ կոնկրետ նշանակություն)',
    quickTipEs: '1 palabra = 1 solo significado',
    quickTipHy: '1 բառ = միայն 1 իմաստ',
  },
  {
    id: 'polisemia',
    conceptEs: 'Polisemia',
    conceptHy: 'Բազմիմաստություն',
    defEs: 'Una misma palabra tiene varios significados relacionados.',
    defHy: 'Նույն բառը ունի մի քանի փոխկապակցված իմաստներ։',
    exampleEs: 'banco (asiento / entidad financiera), cabeza (parte del cuerpo / líder)',
    exampleHy: 'banco (նստարան կամ դրամատուն), cabeza (մարդու գլուխ կամ թիմի ղեկավար)',
    quickTipEs: '1 palabra = varios significados',
    quickTipHy: '1 բառ = մի քանի իմաստներ',
  },
  {
    id: 'sinonimia',
    conceptEs: 'Sinonimia',
    conceptHy: 'Հոմանիշներ',
    defEs: 'Palabras con significado igual o parecido.',
    defHy: 'Նույն կամ մոտ իմաստ ունեցող բառեր։',
    exampleEs: 'rápido = veloz, contento = feliz, bonito = hermoso',
    exampleHy: 'rápido = veloz (արագ), contento = feliz (ուրախ), bonito = hermoso (գեղեցիկ)',
    quickTipEs: 'Distintas palabras, significado casi idéntico',
    quickTipHy: 'Տարբեր բառեր, գրեթե նույն իմաստով',
  },
  {
    id: 'antonimia',
    conceptEs: 'Antonimia',
    conceptHy: 'Հականիշներ',
    defEs: 'Palabras con significados opuestos.',
    defHy: 'Հակառակ իմաստ ունեցող բառեր։',
    exampleEs: 'alto ↔ bajo, entrar ↔ salir, difícil ↔ fácil, frío ↔ caliente',
    exampleHy: 'alto ↔ bajo (բարձր ↔ ցածր), entrar ↔ salir (մտնել ↔ դուրս գալ), difícil ↔ fácil (դժվար ↔ հեշտ)',
    quickTipEs: 'Significados contrarios y opuestos',
    quickTipHy: 'Հակադիր, իրար ժխտող իմաստներ',
  },
  {
    id: 'campo-semantico',
    conceptEs: 'Campo semántico',
    conceptHy: 'Իմաստային դաշտ',
    defEs: 'Palabras de la misma categoría que comparten un significado común o pertenecen al mismo tema.',
    defHy: 'Նույն թեմային և նույն քերականական դասին պատկանող բառերի խումբ։',
    exampleEs: 'rosa, tulipán, margarita, clavel (campo de flores); delantero, portero, defensa (fútbol)',
    exampleHy: 'rosa, tulipán, margarita (ծաղիկների դաշտ); delantero, portero (ֆուտբոլային դիրքեր)',
    quickTipEs: 'Mismo tema, raíces DIFERENTES',
    quickTipHy: 'Նույն թեման է, բայց ՏԱՐԲԵՐ արմատներ',
  },
  {
    id: 'familia-lexica',
    conceptEs: 'Familia léxica',
    conceptHy: 'Բառակազմական ընտանիք',
    defEs: 'Palabras que comparten la misma raíz (lexema).',
    defHy: 'Նույն արմատն ունեցող բառեր։',
    exampleEs: 'pan, panadero, panadería, panecillo (raíz: pan-); flor, florero, florista (raíz: flor-)',
    exampleHy: 'pan, panadero, panadería (արմատը՝ pan-); flor, florero, florista (արմատը՝ flor-)',
    quickTipEs: 'Misma RAÍZ morfológica',
    quickTipHy: 'Ունեն ՆՈՒՅՆ արմատը',
  },
];

export const QUICK_EXAM_TIPS = [
  {
    questionEs: '¿Significan casi lo mismo?',
    questionHy: 'Գրեթե նո՞ւյն իմաստն ունեն։',
    answerEs: 'Sinónimos (Հոմանիշներ)',
    answerHy: 'Հոմանիշներ',
  },
  {
    questionEs: '¿Significan lo contrario?',
    questionHy: 'Հակառա՞կ իմաստն ունեն։',
    answerEs: 'Antónimos (Հականիշներ)',
    answerHy: 'Հականիշներ',
  },
  {
    questionEs: '¿Una palabra tiene varios significados?',
    questionHy: 'Մեկ բառը մի քանի՞ իմաստ ունի։',
    answerEs: 'Polisemia (Բազմիմաստություն)',
    answerHy: 'Բազմիմաստություն',
  },
  {
    questionEs: '¿Son palabras distintas de un mismo tema?',
    questionHy: 'Տարբեր բառեր են նույն թեմայի՞ց։',
    answerEs: 'Campo semántico (Իմաստային դաշտ)',
    answerHy: 'Իմաստային դաշտ (արմատները տարբեր են)',
  },
  {
    questionEs: '¿Tienen la misma raíz?',
    questionHy: 'Նույն արմա՞տն ունեն։',
    answerEs: 'Familia léxica (Բառակազմական ընտանիք)',
    answerHy: 'Բառակազմական ընտանիք (նույն արմատը)',
  },
];

// EXAMEN 1: 12 Exercises + Mini Examen
export const EXAMEN_1_SECTIONS: ExerciseSection[] = [
  {
    id: 'e1-s1',
    titleEs: 'Ejercicio 1 — Sinónimos',
    titleHy: 'Վարժություն 1 — Հոմանիշներ',
    subtitleEs: 'Palabras con significado igual o semejante',
    subtitleHy: 'Նույն կամ մոտ իմաստ ունեցող բառեր',
    questions: [
      {
        id: 'e1-q1',
        number: 1,
        category: 'sinonimos',
        categoryLabelEs: 'Sinónimo',
        categoryLabelHy: 'Հոմանիշ',
        promptEs: '¿Cuál es un sinónimo de rápido?',
        promptHy: 'Ո՞րն է rápido բառի հոմանիշը։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. lento', textHy: 'դանդաղ' },
          { id: 'B', textEs: 'B. veloz', textHy: 'արագ' },
          { id: 'C', textEs: 'C. pequeño', textHy: 'փոքր' },
          { id: 'D', textEs: 'D. débil', textHy: 'թույլ' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. veloz — rápido significa que se mueve a gran velocidad.',
        correctAnswerHy: 'B. veloz — արագ։ «rápido» և «veloz» նշանակում են մեծ արագությամբ շարժվող։',
        explanationEs: 'Rápido y veloz son sinónimos totales en este contexto. Lento es el antónimo.',
        explanationHy: '«rápido» և «veloz» բառերը հոմանիշներ են։ Իսկ «lento»-ն դրա հականիշն է։',
      },
      {
        id: 'e1-q2',
        number: 2,
        category: 'sinonimos',
        categoryLabelEs: 'Sinónimo',
        categoryLabelHy: 'Հոմանիշ',
        promptEs: '¿Cuál es un sinónimo de contento?',
        promptHy: 'Ո՞րն է contento բառի հոմանիշը։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. feliz', textHy: 'ուրախ, երջանիկ' },
          { id: 'B', textEs: 'B. triste', textHy: 'տխուր' },
          { id: 'C', textEs: 'C. enfadado', textHy: 'զայրացած' },
          { id: 'D', textEs: 'D. difícil', textHy: 'դժվար' },
        ],
        correctOptionId: 'A',
        correctAnswerEs: 'A. feliz — contento expresa alegría y satisfacción.',
        correctAnswerHy: 'A. feliz — ուրախ։ «contento» և «feliz» արտահայտում են ուրախություն։',
        explanationEs: 'Feliz es el sinónimo más adecuado. Triste y enfadado expresan estados contrarios.',
        explanationHy: '«contento» = «feliz» (ուրախ)։ «triste» (տխուր) և «enfadado» (բարկացած) հականիշային են։',
      },
      {
        id: 'e1-q3',
        number: 3,
        category: 'sinonimos',
        categoryLabelEs: 'Sinónimo',
        categoryLabelHy: 'Հոմանիշ',
        promptEs: '¿Qué palabra puede sustituir a bonito sin cambiar mucho el significado?',
        promptHy: 'Ո՞ր բառը կարող է փոխարինել bonito բառին՝ առանց իմաստը էապես փոխելու։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. hermoso', textHy: 'գեղեցիկ' },
          { id: 'B', textEs: 'B. feo', textHy: 'տգեղ' },
          { id: 'C', textEs: 'C. largo', textHy: 'երկար' },
          { id: 'D', textEs: 'D. antiguo', textHy: 'հին / հնագույն' },
        ],
        correctOptionId: 'A',
        correctAnswerEs: 'A. hermoso — bello, estéticamente agradable.',
        correctAnswerHy: 'A. hermoso — գեղեցիկ։ «bonito»-ն կարող է փոխարինվել «hermoso» բառով։',
        explanationEs: 'Bonito y hermoso son adjetivos sinónimos referidos a la belleza. Feo es su antónimo.',
        explanationHy: '«bonito» և «hermoso» հոմանիշ ածականներ են։ «feo»-ն հականիշն է (տգեղ)։',
      },
    ],
  },
  {
    id: 'e1-s2',
    titleEs: 'Ejercicio 2 — Antónimos',
    titleHy: 'Վարժություն 2 — Հականիշներ',
    subtitleEs: 'Palabras con significado opuesto',
    subtitleHy: 'Հակառակ իմաստ ունեցող բառեր',
    questions: [
      {
        id: 'e1-q4',
        number: 4,
        category: 'antonimos',
        categoryLabelEs: 'Antónimo',
        categoryLabelHy: 'Հականիշ',
        promptEs: '¿Cuál es el antónimo de alto?',
        promptHy: 'Ո՞րն է alto բառի հականիշը։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. grande', textHy: 'մեծ' },
          { id: 'B', textEs: 'B. bajo', textHy: 'ցածր / կարճահասակ' },
          { id: 'C', textEs: 'C. largo', textHy: 'երկար' },
          { id: 'D', textEs: 'D. fuerte', textHy: 'ուժեղ' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. bajo — de poca estatura o altura.',
        correctAnswerHy: 'B. bajo — ցածր / կարճահասակ։',
        explanationEs: 'El antónimo directo de alto es bajo.',
        explanationHy: '«alto» (բարձրահասակ/բարձր) բառի ուղիղ հականիշն է «bajo» (ցածր/կարճահասակ)։',
      },
      {
        id: 'e1-q5',
        number: 5,
        category: 'antonimos',
        categoryLabelEs: 'Antónimo',
        categoryLabelHy: 'Հականիշ',
        promptEs: '¿Cuál es el antónimo de entrar?',
        promptHy: 'Ո՞րն է entrar բառի հականիշը։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. llegar', textHy: 'ժամանել' },
          { id: 'B', textEs: 'B. venir', textHy: 'գալ' },
          { id: 'C', textEs: 'C. salir', textHy: 'դուրս գալ' },
          { id: 'D', textEs: 'D. abrir', textHy: 'բացել' },
        ],
        correctOptionId: 'C',
        correctAnswerEs: 'C. salir — pasar de dentro a fuera.',
        correctAnswerHy: 'C. salir — դուրս գալ։',
        explanationEs: 'Entrar (pasar al interior) tiene como antónimo salir (pasar al exterior).',
        explanationHy: '«entrar» (ներս մտնել) բառի հակառակ գործողությունն է «salir» (դուրս գալ)։',
      },
      {
        id: 'e1-q6',
        number: 6,
        category: 'antonimos',
        categoryLabelEs: 'Antónimo en contexto',
        categoryLabelHy: 'Հականիշ համատեքստում',
        promptEs: 'Completa con un antónimo:\n"El ejercicio no era difícil; era ______."',
        promptHy: 'Լրացրո՛ւ հականիշով.\n«Վարժությունը դժվար չէր, այն ______ էր։»',
        type: 'open',
        correctAnswerEs: 'fácil',
        correctAnswerHy: 'հեշտ (fácil)',
        explanationEs: 'El antónimo de difícil es fácil.',
        explanationHy: '«difícil» (դժվար) բառի հականիշն է «fácil» (հեշտ)։',
      },
    ],
  },
  {
    id: 'e1-s3',
    titleEs: 'Ejercicio 3 — Palabras polisémicas',
    titleHy: 'Վարժություն 3 — Բազմիմաստ բառեր',
    subtitleEs: 'Una misma palabra con varios significados relacionados',
    subtitleHy: 'Նույն բառը՝ մի քանի փոխկապակցված իմաստներով',
    questions: [
      {
        id: 'e1-q7',
        number: 7,
        category: 'polisemia',
        categoryLabelEs: 'Polisemia',
        categoryLabelHy: 'Բազմիմաստություն',
        promptEs: 'Lee las dos oraciones:\n1. "Me duele la cabeza."\n2. "La cabeza del equipo habló con los jugadores."\n¿Qué ocurre con la palabra cabeza?',
        promptHy: 'Կարդա՛ երկու նախադասությունները.\n1. «Գլուխս ցավում է։»\n2. «Թիմի ղեկավարը խոսեց խաղացողների հետ։»\nԻ՞նչ է տեղի ունենում cabeza բառի հետ։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. Es un antónimo.', textHy: 'Հականիշ է։' },
          { id: 'B', textEs: 'B. Es polisémica.', textHy: 'Բազմիմաստ բառ է։' },
          { id: 'C', textEs: 'C. Es un sinónimo.', textHy: 'Հոմանիշ է։' },
          { id: 'D', textEs: 'D. No tiene significado.', textHy: 'Իմաստ չունի։' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. Es polisémica — Բազմիմաստ բառ է։',
        correctAnswerHy: 'B. Es polisémica — Բազմիմաստ բառ է։',
        explanationEs: 'Cabeza tiene dos significados aquí: la parte superior del cuerpo y el líder o jefe de un grupo.',
        explanationHy: '«cabeza» բառը այստեղ երկու տարբեր իմաստ ունի՝ մարմնի մաս (գլուխ) և խմբի առաջնորդ/ղեկավար։',
      },
      {
        id: 'e1-q8',
        number: 8,
        category: 'polisemia',
        categoryLabelEs: 'Palabra polisémica',
        categoryLabelHy: 'Բազմիմաստ բառ',
        promptEs: 'Lee:\n"El banco está junto al parque."\n"Mi madre fue al banco a sacar dinero."\n¿Qué palabra tiene varios significados?',
        promptHy: 'Կարդա՛.\n«Նստարանը գտնվում է զբոսայգու մոտ։»\n«Մայրիկս գնաց բանկ՝ գումար հանելու։»\nՈ՞ր բառն ունի մի քանի իմաստ։',
        type: 'open',
        correctAnswerEs: 'banco',
        correctAnswerHy: 'banco (նստարան / բանկ-դրամատուն)',
        explanationEs: 'Banco significa "mueble para sentarse" en la primera frase y "entidad de crédito/financiera" en la segunda.',
        explanationHy: '«banco» բառը առաջին նախադասության մեջ նստարան է, երկրորդում՝ դրամատուն (բանկ)։',
      },
      {
        id: 'e1-q9',
        number: 9,
        category: 'polisemia',
        categoryLabelEs: 'Explicación de significados',
        categoryLabelHy: 'Իմաստների բացատրություն',
        promptEs: 'Explica los dos significados de hoja:\n"La hoja del árbol es verde."\n"Escribe tu nombre en una hoja."',
        promptHy: 'Բացատրի՛ր hoja բառի երկու իմաստները.\n«Ծառի տերևը կանաչ է։»\n«Գրի՛ր քո անունը թղթի վրա։»',
        type: 'open',
        correctAnswerEs: '1. Parte de una planta (տերև) | 2. Hoja de papel (թղթի թերթ) ➡️ Palabra polisémica',
        correctAnswerHy: '1. Ծառի կամ բույսի տերև։\n2. Թղթի թերթ։\n➡️ Palabra polisémica (Բազմիմաստ բառ)։',
        explanationEs: 'La palabra hoja tiene múltiples acepciones: órgano vegetal y lámina delgada de papel.',
        explanationHy: '«hoja» բառը նշանակում է ինչպես բույսի տերև, այնպես էլ գրելու թերթ։ Դա բազմիմաստություն է։',
      },
    ],
  },
  {
    id: 'e1-s4',
    titleEs: 'Ejercicio 4 — Monosemia o polisemia',
    titleHy: 'Վարժություն 4 — Մենիմա՞ստ, թե՞ բազմիմաստ',
    subtitleEs: 'Determina si la palabra tiene un solo significado o varios',
    subtitleHy: 'Որոշի՛ր՝ բառն ունի մեկ, թե մի քանի իմաստ',
    questions: [
      {
        id: 'e1-q10',
        number: 10,
        category: 'monosemia',
        categoryLabelEs: 'Clasificación',
        categoryLabelHy: 'Դասակարգում',
        promptEs: 'Termómetro — ¿Es monosémica o polisémica?',
        promptHy: 'Termómetro (ջերմաչափ) — մենիմա՞ստ է, թե՞ բազմիմաստ։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. Monosémica', textHy: 'Մենիմաստ' },
          { id: 'B', textEs: 'B. Polisémica', textHy: 'Բազմիմաստ' },
        ],
        correctOptionId: 'A',
        correctAnswerEs: 'A. Monosémica',
        correctAnswerHy: 'A. Monosémica (Մենիմաստ)',
        explanationEs: 'Termómetro tiene un único significado técnico: aparato que mide la temperatura.',
        explanationHy: '«ջերմաչափ» — հիմնականում ունի մեկ կոնկրետ գիտական/գործնական նշանակություն։',
      },
      {
        id: 'e1-q11',
        number: 11,
        category: 'polisemia',
        categoryLabelEs: 'Clasificación',
        categoryLabelHy: 'Դասակարգում',
        promptEs: 'Banco — ¿Es monosémica o polisémica?',
        promptHy: 'Banco (նստարան / դրամատուն) — մենիմա՞ստ է, թե՞ բազմիմաստ։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. Monosémica', textHy: 'Մենիմաստ' },
          { id: 'B', textEs: 'B. Polisémica', textHy: 'Բազմիմաստ' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. Polisémica',
        correctAnswerHy: 'B. Polisémica (Բազմիմաստ)',
        explanationEs: 'Banco posee múltiples significados: asiento, entidad bancaria, banco de peces, etc.',
        explanationHy: 'Ունի բազմաթիվ իմաստներ՝ նստարան, դրամատուն, ձկների վտառ և այլն։',
      },
      {
        id: 'e1-q12',
        number: 12,
        category: 'polisemia',
        categoryLabelEs: 'Clasificación',
        categoryLabelHy: 'Դասակարգում',
        promptEs: 'Ratón — Puede ser un animal o un dispositivo del ordenador. ¿Qué es?',
        promptHy: 'Ratón — Կարող է լինել կենդանի կամ համակարգչային մկնիկ։ Ի՞նչ է այն։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. Monosémica', textHy: 'Մենիմաստ' },
          { id: 'B', textEs: 'B. Polisémica', textHy: 'Բազմիմաստ' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. Polisémica — Բազմիմաստ',
        correctAnswerHy: 'B. Polisémica — Բազմիմաստ',
        explanationEs: 'Tiene dos significados muy conocidos: el roedor (animal) y el ratón del ordenador.',
        explanationHy: 'Կարող է նշանակել կենդանի (կրծող) կամ համակարգչային մկնիկ։',
      },
    ],
  },
  {
    id: 'e1-s5',
    titleEs: 'Ejercicio 5 — Campo semántico',
    titleHy: 'Վարժություն 5 — Իմաստային դաշտ',
    subtitleEs: 'Palabras del mismo tema y categoría gramatical',
    subtitleHy: 'Նույն թեմային պատկանող բառերի խումբ',
    questions: [
      {
        id: 'e1-q13',
        number: 13,
        category: 'campo_semantico',
        categoryLabelEs: 'Campo semántico',
        categoryLabelHy: 'Իմաստային դաշտ',
        promptEs: '¿Qué palabras pertenecen al campo semántico de deportes?',
        promptHy: 'Ո՞ր բառերն են պատկանում «սպորտ» (deportes) իմաստային դաշտին։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. fútbol, tenis, baloncesto, natación', textHy: 'ֆուտբոլ, թենիս, բասկետբոլ, լող' },
          { id: 'B', textEs: 'B. mesa, silla, sofá, cama', textHy: 'սեղան, աթոռ, բազմոց, մահճակալ' },
          { id: 'C', textEs: 'C. perro, gato, caballo, conejo', textHy: 'շուն, կատու, ձի, նապաստակ' },
          { id: 'D', textEs: 'D. rojo, verde, azul, amarillo', textHy: 'կարմիր, կանաչ, կապույտ, դեղին' },
        ],
        correctOptionId: 'A',
        correctAnswerEs: 'A. fútbol, tenis, baloncesto, natación',
        correctAnswerHy: 'A. fútbol, tenis, baloncesto, natación (Դրանք բոլորը սպորտաձևեր են)։',
        explanationEs: 'Todas son disciplinas deportivas (mismo tema y categoría). Las otras opciones son muebles, animales y colores.',
        explanationHy: 'Բոլորը սպորտաձևեր են։ Մյուս տարբերակները կահույք են, կենդանիներ կամ գույներ։',
      },
      {
        id: 'e1-q14',
        number: 14,
        category: 'campo_semantico',
        categoryLabelEs: 'Campo semántico',
        categoryLabelHy: 'Իմաստային դաշտ',
        promptEs: 'delantero – portero – defensa – centrocampista\n¿A qué campo semántico pertenecen?',
        promptHy: 'delantero – portero – defensa – centrocampista\nՈ՞ր իմաստային դաշտին են պատկանում։',
        type: 'open',
        correctAnswerEs: 'Posiciones de fútbol (jugadores en el campo)',
        correctAnswerHy: 'Ֆուտբոլային դիրքեր (Posiciones de fútbol)',
        explanationEs: 'Todos son roles o posiciones de jugadores en un equipo de fútbol.',
        explanationHy: 'Դրանք ֆուտբոլի դաշտում խաղացողների դիրքերն են (հարձակվող, դարպասապահ, պաշտպան, կիսապաշտպան)։',
      },
      {
        id: 'e1-q15',
        number: 15,
        category: 'intruso',
        categoryLabelEs: 'Encuentra el intruso',
        categoryLabelHy: 'Գտի՛ր ավելորդ բառը',
        promptEs: '¿Cuál NO pertenece al mismo campo semántico?\nmanzana – pera – plátano – camiseta',
        promptHy: 'Ո՞ր բառը ՉԻ պատկանում նույն իմաստային դաշտին.\nmanzana – pera – plátano – camiseta',
        type: 'open',
        correctAnswerEs: 'camiseta',
        correctAnswerHy: 'camiseta (շապիկ, որովհետև մյուսները մրգեր են)',
        explanationEs: 'Camiseta es una prenda de vestir; manzana, pera y plátano pertenecen al campo semántico de las frutas.',
        explanationHy: '«camiseta»-ն հագուստ է (շապիկ), իսկ մյուս երեքը մրգեր են։',
      },
    ],
  },
  {
    id: 'e1-s6',
    titleEs: 'Ejercicio 6 — Familia léxica',
    titleHy: 'Վարժություն 6 — Բառակազմական ընտանիք',
    subtitleEs: 'Palabras que comparten la misma raíz morfológica',
    subtitleHy: 'Նույն արմատն ունեցող բառերի խումբ',
    questions: [
      {
        id: 'e1-q16',
        number: 16,
        category: 'familia_lexica',
        categoryLabelEs: 'Familia léxica',
        categoryLabelHy: 'Բառակազմական ընտանիք',
        promptEs: '¿Qué palabras pertenecen a la familia léxica de pan?',
        promptHy: 'Ո՞ր բառերն են պատկանում pan բառի բառակազմական ընտանիքին։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. pan, panadero, panadería', textHy: 'հաց, հացթուխ, հացի փուռ' },
          { id: 'B', textEs: 'B. pan, leche, queso', textHy: 'հաց, կաթ, պանիր' },
          { id: 'C', textEs: 'C. pan, mesa, comer', textHy: 'հաց, սեղան, ուտել' },
          { id: 'D', textEs: 'D. pan, fruta, mercado', textHy: 'հաց, միրգ, շուկա' },
        ],
        correctOptionId: 'A',
        correctAnswerEs: 'A. pan – panadero – panadería',
        correctAnswerHy: 'A. pan – panadero – panadería (ունեն նույն արմատը՝ pan-)։',
        explanationEs: 'Comparten la misma raíz pan-. Las opciones B, C y D tienen raíces distintas (relación semántica, no morfológica).',
        explanationHy: 'Բոլորն ունեն նույն «pan-» արմատը։ Կաթը և պանիրը ուտելիքի իմաստային դաշտ են, ոչ թե նույն արմատը։',
      },
      {
        id: 'e1-q17',
        number: 17,
        category: 'intruso',
        categoryLabelEs: 'Palabra intrusa',
        categoryLabelHy: 'Ավելորդ բառ',
        promptEs: 'Encuentra la palabra que NO pertenece a la familia de mar:\nmarino – marinero – marítimo – montaña',
        promptHy: 'Գտի՛ր այն բառը, որը ՉԻ պատկանում mar բառի ընտանիքին.\nmarino – marinero – marítimo – montaña',
        type: 'open',
        correctAnswerEs: 'montaña',
        correctAnswerHy: 'montaña (լեռ, որովհետև չունի mar- արմատը)',
        explanationEs: 'Montaña no comparte la raíz mar-. Marino, marinero y marítimo sí provienen de mar.',
        explanationHy: '«montaña» (լեռ) բառը չունի mar- արմատը։ Մյուսները ծովային բառեր են mar- արմատով։',
      },
      {
        id: 'e1-q18',
        number: 18,
        category: 'familia_lexica',
        categoryLabelEs: 'Completa la familia',
        categoryLabelHy: 'Լրացրո՛ւ ընտանիքը',
        promptEs: 'Completa una familia léxica:\ndeporte → deportivo → ______',
        promptHy: 'Լրացրո՛ւ բառակազմական ընտանիքը.\ndeporte → deportivo → ______',
        type: 'open',
        correctAnswerEs: 'deportista / deportivamente',
        correctAnswerHy: 'deportista (մարզիկ) կամ deportivamente (մարզականորեն)',
        explanationEs: 'Deportista y deportivamente comparten la misma raíz deport-.',
        explanationHy: '«deportista» (մարզիկ) ունի նույն «deport-» արմատը։',
      },
    ],
  },
  {
    id: 'e1-s7',
    titleEs: 'Ejercicio 7 — Campo semántico o familia léxica?',
    titleHy: 'Վարժություն 7 — Իմաստային դա՞շտ, թե՞ բառակազմական ընտանիք',
    subtitleEs: '¡Diferencia clave para el examen de 7º grado!',
    subtitleHy: 'Սա քննության համար շատ կարևոր տարբերություն է։',
    noteEs: 'Regla de oro: flor – florista – florero = misma raíz → familia léxica | rosa – tulipán – clavel = mismo tema, raíces diferentes → campo semántico',
    noteHy: 'Ոսկե կանոն. flor – florista – florero = նույն արմատ → բառակազմական ընտանիք | rosa – tulipán – clavel = նույն թեմա, տարբեր արմատներ → իմաստային դաշտ',
    questions: [
      {
        id: 'e1-q19',
        number: 19,
        category: 'clasificacion',
        categoryLabelEs: 'Familia léxica',
        categoryLabelHy: 'Բառակազմական ընտանիք',
        promptEs: 'flor – florero – florista – florecer\n¿Qué forman?',
        promptHy: 'flor – florero – florista – florecer\nԻ՞նչ են կազմում։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. Una familia léxica', textHy: 'Բառակազմական ընտանիք' },
          { id: 'B', textEs: 'B. Un campo semántico', textHy: 'Իմաստային դաշտ' },
        ],
        correctOptionId: 'A',
        correctAnswerEs: 'A. Una familia léxica',
        correctAnswerHy: 'A. Բառակազմական ընտանիք, որովհետև բոլոր բառերն ունեն նույն արմատը՝ flor-։',
        explanationEs: 'Todas tienen la raíz flor-. Por eso es una familia léxica.',
        explanationHy: 'Բոլորն ունեն նույն «flor-» արմատը (ծաղիկ, ծաղկաման, ծաղկավաճառ, ծաղկել)։',
      },
      {
        id: 'e1-q20',
        number: 20,
        category: 'clasificacion',
        categoryLabelEs: 'Campo semántico',
        categoryLabelHy: 'Իմաստային դաշտ',
        promptEs: 'rosa – tulipán – margarita – clavel\n¿Qué forman?',
        promptHy: 'rosa – tulipán – margarita – clavel\nԻ՞նչ են կազմում։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. Una familia léxica', textHy: 'Բառակազմական ընտանիք' },
          { id: 'B', textEs: 'B. Un campo semántico de flores', textHy: 'Ծաղիկների իմաստային դաշտ' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. Un campo semántico de flores',
        correctAnswerHy: 'B. Ծաղիկների իմաստային դաշտ (նույն թեման է, բայց տարբեր արմատներ)։',
        explanationEs: 'Son nombres de flores (mismo tema) pero tienen raíces totalmente distintas.',
        explanationHy: 'Վարդ, կակաչ, մարգարիտածաղիկ, մեխակ՝ բոլորը ծաղիկներ են (նույն թեման), բայց արմատները տարբեր են։',
      },
    ],
  },
  {
    id: 'e1-s8',
    titleEs: 'Ejercicio 8 — Significado según el contexto',
    titleHy: 'Վարժություն 8 — Իմաստը ըստ համատեքստի',
    subtitleEs: 'El significado de una palabra depende de la frase donde se usa',
    subtitleHy: 'Բառի իմաստը կախված է նախադասության համատեքստից',
    questions: [
      {
        id: 'e1-q21',
        number: 21,
        category: 'contexto',
        categoryLabelEs: 'Contexto',
        categoryLabelHy: 'Համատեքստ',
        promptEs: 'El portero paró el balón.\n¿Qué significa paró aquí?',
        promptHy: 'El portero paró el balón. (Դարպասապահը կանգնեցրեց գնդակը։)\nԻ՞նչ է նշանակում paró այստեղ։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. empezó a correr', textHy: 'սկսեց վազել' },
          { id: 'B', textEs: 'B. detuvo', textHy: 'կանգնեցրեց' },
          { id: 'C', textEs: 'C. lanzó', textHy: 'նետեց' },
          { id: 'D', textEs: 'D. perdió', textHy: 'կորցրեց' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. detuvo — կանգնեցրեց',
        correctAnswerHy: 'B. detuvo — կանգնեցրեց (Դարպասապահը կանգնեցրեց գնդակը)։',
        explanationEs: 'En el fútbol, parar el balón significa detener su trayectoria para evitar el gol.',
        explanationHy: '«paró» այստեղ նշանակում է կանգնեցրեց, կասեցրեց գնդակը։',
      },
      {
        id: 'e1-q22',
        number: 22,
        category: 'contexto',
        categoryLabelEs: 'Expresión coloquial',
        categoryLabelHy: 'Դարձվածքային իմաստ',
        promptEs: 'Pedro está hecho polvo después del entrenamiento.\n¿Qué significa aquí estar hecho polvo?',
        promptHy: 'Pedro está hecho polvo después del entrenamiento.\nԻ՞նչ է նշանակում estar hecho polvo այստեղ։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. estar muy cansado', textHy: 'շատ հոգնած լինել' },
          { id: 'B', textEs: 'B. estar muy feliz', textHy: 'շատ ուրախ լինել' },
          { id: 'C', textEs: 'C. estar limpio', textHy: 'մաքուր լինել' },
          { id: 'D', textEs: 'D. estar enfadado', textHy: 'զայրացած լինել' },
        ],
        correctOptionId: 'A',
        correctAnswerEs: 'A. estar muy cansado — շատ հոգնած լինել',
        correctAnswerHy: 'A. estar muy cansado — շատ հոգնած, ուժասպառ լինել։',
        explanationEs: 'La expresión figurada "estar hecho polvo" denota un agotamiento físico extremo.',
        explanationHy: '«estar hecho polvo» իսպաներեն հայտնի դարձվածք է, որը նշանակում է ուժասպառ լինել, շատ հոգնել։',
      },
      {
        id: 'e1-q23',
        number: 23,
        category: 'contexto',
        categoryLabelEs: 'Contexto deportivo',
        categoryLabelHy: 'Սպորտային համատեքստ',
        promptEs: 'El delantero rompió el empate.\n¿Qué significa?',
        promptHy: 'El delantero rompió el empate. (Հարձակվողը խախտեց ոչ-ոքին։)\nԻ՞նչ է նշանակում այս նախադասությունը։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. rompió un objeto físico', textHy: 'ֆիզիկական առարկա կոտրեց' },
          { id: 'B', textEs: 'B. cambió el resultado y puso a su equipo por delante', textHy: 'փոխեց հավասար հաշիվը և իր թիմին առաջ մղեց' },
          { id: 'C', textEs: 'C. salió del estadio', textHy: 'մարզադաշտից դուրս եկավ' },
          { id: 'D', textEs: 'D. terminó su carrera deportiva', textHy: 'ավարտեց մարզական կարիերան' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. Cambió el resultado y puso a su equipo por delante',
        correctAnswerHy: 'B. Հարձակվողը փոխեց հավասար հաշիվը և իր թիմին առաջ մղեց։',
        explanationEs: '"Romper el empate" significa marcar un gol que desempata el marcador a favor de un equipo.',
        explanationHy: 'Ոչ-ոքին կոտրել/խախտել նշանակում է գոլ խփել և թիմին առաջ մղել։',
      },
    ],
  },
  {
    id: 'e1-s9',
    titleEs: 'Ejercicio 9 — Sustituye por un sinónimo',
    titleHy: 'Վարժություն 9 — Փոխարինի՛ր հոմանիշով',
    subtitleEs: 'Reemplaza la palabra destacada sin alterar el sentido',
    subtitleHy: 'Փոխարինի՛ր բառը առանց նախադասության իմաստը փոխելու',
    questions: [
      {
        id: 'e1-q24',
        number: 24,
        category: 'sinonimos',
        categoryLabelEs: 'Sustitución',
        categoryLabelHy: 'Փոխարինում',
        promptEs: 'El jugador estaba muy contento después de ganar.\nSustituye la palabra contento.',
        promptHy: 'El jugador estaba muy contento después de ganar.\nՓոխարինի՛ր contento բառը հոմանիշով։',
        type: 'open',
        correctAnswerEs: 'El jugador estaba muy feliz después de ganar.',
        correctAnswerHy: 'El jugador estaba muy feliz después de ganar. (Խաղացողը հաղթելուց հետո շատ ուրախ էր)։',
        explanationEs: 'Feliz sustituye a contento manteniendo el sentido exacto.',
        explanationHy: '«contento» բառի լավագույն հոմանիշը «feliz»-ն է։',
      },
      {
        id: 'e1-q25',
        number: 25,
        category: 'sinonimos',
        categoryLabelEs: 'Sustitución',
        categoryLabelHy: 'Փոխարինում',
        promptEs: 'El coche es muy rápido.\nSustituye la palabra rápido.',
        promptHy: 'El coche es muy rápido.\nՓոխարինի՛ր rápido բառը հոմանիշով։',
        type: 'open',
        correctAnswerEs: 'El coche es muy veloz.',
        correctAnswerHy: 'El coche es muy veloz. (Մեքենան շատ արագ է)։',
        explanationEs: 'Veloz es el adjetivo sinónimo de rápido.',
        explanationHy: '«rápido» ածականի հոմանիշն է «veloz»։',
      },
    ],
  },
  {
    id: 'e1-s10',
    titleEs: 'Ejercicio 10 — Cambia por el antónimo',
    titleHy: 'Վարժություն 10 — Փոխարինի՛ր հականիշով',
    subtitleEs: 'Escribe la frase con el significado contrario',
    subtitleHy: 'Փոխարինի՛ր հակառակ իմաստ ունեցող բառով',
    questions: [
      {
        id: 'e1-q26',
        number: 26,
        category: 'antonimos',
        categoryLabelEs: 'Antónimo',
        categoryLabelHy: 'Հականիշ',
        promptEs: 'El estadio estaba lleno.\nEscribe el antónimo de lleno.',
        promptHy: 'El estadio estaba lleno.\nԳրի՛ր lleno բառի հականիշը։',
        type: 'open',
        correctAnswerEs: 'vacío (El estadio estaba vacío)',
        correctAnswerHy: 'vacío — դատարկ (El estadio estaba vacío — Մարզադաշտը դատարկ էր)։',
        explanationEs: 'Lleno (ocupado en su totalidad) se opone a vacío (sin nadie ni nada dentro).',
        explanationHy: '«lleno» (լիքը, լեցուն) բառի հականիշն է «vacío» (դատարկ)։',
      },
      {
        id: 'e1-q27',
        number: 27,
        category: 'antonimos',
        categoryLabelEs: 'Antónimo',
        categoryLabelHy: 'Հականիշ',
        promptEs: 'El ejercicio era fácil.\nEscribe el antónimo de fácil.',
        promptHy: 'El ejercicio era fácil.\nԳրի՛ր fácil բառի հականիշը։',
        type: 'open',
        correctAnswerEs: 'difícil (El ejercicio era difícil)',
        correctAnswerHy: 'difícil — դժվար (հեշտ ↔ դժվար)։',
        explanationEs: 'Fácil tiene como antónimo directo difícil.',
        explanationHy: '«fácil» (հեշտ) ↔ «difícil» (դժվար)։',
      },
    ],
  },
  {
    id: 'e1-s11',
    titleEs: 'Ejercicio 11 — Lee el texto y analiza las palabras',
    titleHy: 'Վարժություն 11 — Կարդա՛ և վերլուծի՛ր տեքստը',
    subtitleEs: 'Comprensión lectora y análisis léxico',
    subtitleHy: 'Ընթերցանություն և բառային վերլուծություն',
    textEs: 'Pablo estaba muy contento porque su equipo había ganado el partido. El encuentro había sido difícil, pero los jugadores fueron rápidos y trabajaron juntos. Al final, todos salieron felices del campo.',
    textHy: 'Պաբլոն շատ ուրախ էր, որովհետև նրա թիմը հաղթել էր խաղը։ Հանդիպումը դժվար էր, բայց խաղացողներն արագ էին և միասին էին աշխատում։ Վերջում բոլորը ուրախ դուրս եկան խաղադաշտից։',
    questions: [
      {
        id: 'e1-q-txt1',
        number: '11.1',
        category: 'texto',
        categoryLabelEs: 'Del texto',
        categoryLabelHy: 'Տեքստից',
        promptEs: '1. Busca en el texto un sinónimo de contento.',
        promptHy: '1. Տեքստում գտի՛ր contento բառի հոմանիշը։',
        type: 'open',
        correctAnswerEs: 'feliz / felices (Al final, todos salieron felices)',
        correctAnswerHy: 'feliz / felices (Վերջում բոլորը ուրախ դուրս եկան)',
        explanationEs: 'En la última oración del texto aparece: "todos salieron felices". Feliz es sinónimo de contento.',
        explanationHy: 'Տեքստի վերջին նախադասության մեջ կա «felices» բառը, որը «contento»-ի հոմանիշն է։',
      },
      {
        id: 'e1-q-txt2',
        number: '11.2',
        category: 'texto',
        categoryLabelEs: 'Del texto',
        categoryLabelHy: 'Տեքստից',
        promptEs: '2. Busca palabras en el texto relacionadas con el fútbol.',
        promptHy: '2. Տեքստում գտի՛ր ֆուտբոլի հետ կապված բառեր։',
        type: 'open',
        correctAnswerEs: 'equipo / partido / jugadores / campo / encuentro',
        correctAnswerHy: 'equipo (թիմ), partido (խաղ), jugadores (խաղացողներ), campo (դաշտ), encuentro (հանդիպում)',
        explanationEs: 'Todas pertenecen al campo semántico del fútbol y los deportes colectivos.',
        explanationHy: 'Դրանք բոլորը ֆուտբոլային բառեր են տեքստից։',
      },
      {
        id: 'e1-q-txt3',
        number: '11.3',
        category: 'texto',
        categoryLabelEs: 'Del texto',
        categoryLabelHy: 'Տեքստից',
        promptEs: '3. Escribe el antónimo de difícil que contrasta con el texto.',
        promptHy: '3. Գրի՛ր difícil բառի հականիշը։',
        type: 'open',
        correctAnswerEs: 'fácil',
        correctAnswerHy: 'fácil (հեշտ)',
        explanationEs: 'Difícil se opone a fácil.',
        explanationHy: '«difícil» (դժվար) բառի հականիշն է «fácil» (հեշտ)։',
      },
      {
        id: 'e1-q-txt4',
        number: '11.4',
        category: 'texto',
        categoryLabelEs: 'Del texto',
        categoryLabelHy: 'Տեքստից',
        promptEs: '4. Escribe un sinónimo de rápidos que se podría usar aquí.',
        promptHy: '4. Գրի՛ր rápidos բառի հոմանիշը։',
        type: 'open',
        correctAnswerEs: 'veloces',
        correctAnswerHy: 'veloces (արագներ)',
        explanationEs: 'Rápidos en plural tiene como sinónimo directo veloces.',
        explanationHy: '«rápidos» (արագներ) բառի հոմանիշն է «veloces»։',
      },
      {
        id: 'e1-q-txt5',
        number: '11.5',
        category: 'texto',
        categoryLabelEs: 'Del texto',
        categoryLabelHy: 'Տեքստից',
        promptEs: '5. ¿“Equipo”, “partido”, “jugador” y “campo” pueden relacionarse con un mismo campo semántico?',
        promptHy: '5. Կարո՞ղ են “equipo”, “partido”, “jugador” և “campo” բառերը վերաբերել նույն իմաստային դաշտին։',
        type: 'open',
        correctAnswerEs: 'Sí, con el campo semántico del fútbol.',
        correctAnswerHy: 'Այո, դրանք կապված են ֆուտբոլի իմաստային դաշտի հետ։',
        explanationEs: 'Comparten el tema de la práctica del deporte de fútbol.',
        explanationHy: 'Այո, նրանք բոլորը պատկանում են ֆուտբոլի իմաստային դաշտին։',
      },
    ],
  },
  {
    id: 'e1-s12',
    titleEs: 'Ejercicio 12 — Encuentra el intruso',
    titleHy: 'Վարժություն 12 — Գտի՛ր ավելորդ բառը',
    subtitleEs: 'Identifica la palabra que no encaja en la serie',
    subtitleHy: 'Գտի՛ր շարքին չհամապատասխանող բառը',
    questions: [
      {
        id: 'e1-q28',
        number: 28,
        category: 'intruso',
        categoryLabelEs: 'Intruso',
        categoryLabelHy: 'Ավելորդ բառ',
        promptEs: 'portero – defensa – delantero – plátano\n¿Cuál es el intruso?',
        promptHy: 'portero – defensa – delantero – plátano\nՈ՞րն է ավելորդ բառը։',
        type: 'open',
        correctAnswerEs: 'plátano',
        correctAnswerHy: 'plátano (բանան, որովհետև մյուսները ֆուտբոլային դիրքեր են)։',
        explanationEs: 'Plátano es una fruta; las demás son posiciones de jugadores de fútbol.',
        explanationHy: '«plátano»-ն միրգ է, մյուսները ֆուտբոլային դիրքեր են։',
      },
      {
        id: 'e1-q29',
        number: 29,
        category: 'intruso',
        categoryLabelEs: 'Intruso',
        categoryLabelHy: 'Ավելորդ բառ',
        promptEs: 'rojo – azul – verde – entrenador\n¿Cuál es el intruso?',
        promptHy: 'rojo – azul – verde – entrenador\nՈ՞րն է ավելորդ բառը։',
        type: 'open',
        correctAnswerEs: 'entrenador',
        correctAnswerHy: 'entrenador (մարզիչ, որովհետև մյուսները գույներ են)։',
        explanationEs: 'Entrenador es una profesión; los demás son nombres de colores.',
        explanationHy: '«entrenador»-ը մարզիչ է, իսկ մյուս բառերը գույներ են։',
      },
      {
        id: 'e1-q30',
        number: 30,
        category: 'intruso',
        categoryLabelEs: 'Intruso',
        categoryLabelHy: 'Ավելորդ բառ',
        promptEs: 'panadero – panadería – pan – futbolista\n¿Cuál es el intruso?',
        promptHy: 'panadero – panadería – pan – futbolista\nՈ՞րն է ավելորդ բառը։',
        type: 'open',
        correctAnswerEs: 'futbolista',
        correctAnswerHy: 'futbolista (ֆուտբոլիստ, որովհետև մյուսները պատկանում են pan բառի ընտանիքին)։',
        explanationEs: 'Futbolista no comparte la raíz pan- con las otras tres palabras.',
        explanationHy: '«futbolista»-ն չունի «pan-» արմատը, մինչդեռ մյուսները pan բառի բառակազմական ընտանիքն են։',
      },
    ],
  },
  {
    id: 'e1-mini-final',
    titleEs: '📝 Mini examen final',
    titleHy: '📝 Փոքր վերջնական քննություն',
    subtitleEs: 'Clasifica cada pareja o grupo de palabras',
    subtitleHy: 'Դասակարգի՛ր յուրաքանչյուր բառազույգը կամ խումբը',
    questions: [
      {
        id: 'e1-mf1',
        number: 'Final 1',
        category: 'clasificacion',
        categoryLabelEs: 'Clasificación',
        categoryLabelHy: 'Դասակարգում',
        promptEs: '1. feliz / contento',
        promptHy: '1. feliz / contento (ուրախ)',
        type: 'choice',
        options: [
          { id: 'S', textEs: 'Sinónimos', textHy: 'Հոմանիշներ' },
          { id: 'A', textEs: 'Antónimos', textHy: 'Հականիշներ' },
          { id: 'P', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'C', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'F', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
        ],
        correctOptionId: 'S',
        correctAnswerEs: 'Sinónimos',
        correctAnswerHy: 'Հոմանիշներ (նույն իմաստն ունեն)',
      },
      {
        id: 'e1-mf2',
        number: 'Final 2',
        category: 'clasificacion',
        categoryLabelEs: 'Clasificación',
        categoryLabelHy: 'Դասակարգում',
        promptEs: '2. subir / bajar',
        promptHy: '2. subir / bajar (բարձրանալ / իջնել)',
        type: 'choice',
        options: [
          { id: 'S', textEs: 'Sinónimos', textHy: 'Հոմանիշներ' },
          { id: 'A', textEs: 'Antónimos', textHy: 'Հականիշներ' },
          { id: 'P', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'C', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'F', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
        ],
        correctOptionId: 'A',
        correctAnswerEs: 'Antónimos',
        correctAnswerHy: 'Հականիշներ (հակառակ գործողություններ)',
      },
      {
        id: 'e1-mf3',
        number: 'Final 3',
        category: 'clasificacion',
        categoryLabelEs: 'Clasificación',
        categoryLabelHy: 'Դասակարգում',
        promptEs: '3. banco: asiento / entidad financiera',
        promptHy: '3. banco: նստարան / դրամատուն',
        type: 'choice',
        options: [
          { id: 'S', textEs: 'Sinónimos', textHy: 'Հոմանիշներ' },
          { id: 'A', textEs: 'Antónimos', textHy: 'Հականիշներ' },
          { id: 'P', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'C', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'F', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
        ],
        correctOptionId: 'P',
        correctAnswerEs: 'Polisemia',
        correctAnswerHy: 'Բազմիմաստ բառ (մեկ բառ՝ մի քանի իմաստով)',
      },
      {
        id: 'e1-mf4',
        number: 'Final 4',
        category: 'clasificacion',
        categoryLabelEs: 'Clasificación',
        categoryLabelHy: 'Դասակարգում',
        promptEs: '4. perro / gato / caballo / conejo',
        promptHy: '4. perro / gato / caballo / conejo (շուն, կատու, ձի, նապաստակ)',
        type: 'choice',
        options: [
          { id: 'S', textEs: 'Sinónimos', textHy: 'Հոմանիշներ' },
          { id: 'A', textEs: 'Antónimos', textHy: 'Հականիշներ' },
          { id: 'P', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'C', textEs: 'Campo semántico de animales', textHy: 'Կենդանիների իմաստային դաշտ' },
          { id: 'F', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
        ],
        correctOptionId: 'C',
        correctAnswerEs: 'Campo semántico de animales',
        correctAnswerHy: 'Կենդանիների իմաստային դաշտ (նույն թեման է, տարբեր արմատներ)',
      },
      {
        id: 'e1-mf5',
        number: 'Final 5',
        category: 'clasificacion',
        categoryLabelEs: 'Clasificación',
        categoryLabelHy: 'Դասակարգում',
        promptEs: '5. pan / panadero / panadería',
        promptHy: '5. pan / panadero / panadería (հաց, հացթուխ, փուռ)',
        type: 'choice',
        options: [
          { id: 'S', textEs: 'Sinónimos', textHy: 'Հոմանիշներ' },
          { id: 'A', textEs: 'Antónimos', textHy: 'Հականիշներ' },
          { id: 'P', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'C', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'F', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
        ],
        correctOptionId: 'F',
        correctAnswerEs: 'Familia léxica',
        correctAnswerHy: 'Նույն բառային ընտանիք (բոլորն ունեն pan- արմատը)',
      },
      {
        id: 'e1-mf6',
        number: 'Final 6',
        category: 'clasificacion',
        categoryLabelEs: 'Clasificación',
        categoryLabelHy: 'Դասակարգում',
        promptEs: '6. frío / caliente',
        promptHy: '6. frío / caliente (սառը / տաք)',
        type: 'choice',
        options: [
          { id: 'S', textEs: 'Sinónimos', textHy: 'Հոմանիշներ' },
          { id: 'A', textEs: 'Antónimos', textHy: 'Հականիշներ' },
          { id: 'P', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'C', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'F', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
        ],
        correctOptionId: 'A',
        correctAnswerEs: 'Antónimos',
        correctAnswerHy: 'Հականիշներ (հակառակ ջերմաստիճան)',
      },
      {
        id: 'e1-mf7',
        number: 'Final 7',
        category: 'clasificacion',
        categoryLabelEs: 'Clasificación',
        categoryLabelHy: 'Դասակարգում',
        promptEs: '7. bonito / hermoso',
        promptHy: '7. bonito / hermoso (գեղեցիկ)',
        type: 'choice',
        options: [
          { id: 'S', textEs: 'Sinónimos', textHy: 'Հոմանիշներ' },
          { id: 'A', textEs: 'Antónimos', textHy: 'Հականիշներ' },
          { id: 'P', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'C', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'F', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
        ],
        correctOptionId: 'S',
        correctAnswerEs: 'Sinónimos',
        correctAnswerHy: 'Հոմանիշներ (նույն իմաստը)',
      },
      {
        id: 'e1-mf8',
        number: 'Final 8',
        category: 'clasificacion',
        categoryLabelEs: 'Clasificación',
        categoryLabelHy: 'Դասակարգում',
        promptEs: '8. hoja: parte de un árbol / papel',
        promptHy: '8. hoja: ծառի տերև / թղթի թերթ',
        type: 'choice',
        options: [
          { id: 'S', textEs: 'Sinónimos', textHy: 'Հոմանիշներ' },
          { id: 'A', textEs: 'Antónimos', textHy: 'Հականիշներ' },
          { id: 'P', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'C', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'F', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
        ],
        correctOptionId: 'P',
        correctAnswerEs: 'Polisemia',
        correctAnswerHy: 'Բազմիմաստ բառ (երկու տարբեր իմաստ)',
      },
    ],
  },
];

// EXAMEN 2: 30 Questions with Context, Classification & Explanations
export const EXAMEN_2_SECTIONS: ExerciseSection[] = [
  {
    id: 'e2-s1',
    titleEs: '1. Elige el sinónimo',
    titleHy: '1. Ընտրի՛ր հոմանիշը',
    questions: [
      {
        id: 'e2-q1',
        number: 1,
        category: 'sinonimos',
        categoryLabelEs: 'Sinónimo',
        categoryLabelHy: 'Հոմանիշ',
        promptEs: '¿Cuál es un sinónimo de comenzar?',
        promptHy: 'Ո՞րն է comenzar բառի հոմանիշը։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. terminar', textHy: 'ավարտել' },
          { id: 'B', textEs: 'B. empezar', textHy: 'սկսել' },
          { id: 'C', textEs: 'C. parar', textHy: 'կանգ առնել' },
          { id: 'D', textEs: 'D. cerrar', textHy: 'փակել' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. empezar — սկսել',
        correctAnswerHy: 'B. empezar — սկսել (comenzar = empezar)',
        explanationEs: 'Comenzar y empezar son verbos sinónimos directos. Terminar y parar son antónimos.',
        explanationHy: '«comenzar» և «empezar» նշանակում են «սկսել»։ «terminar»-ը դրա հականիշն է (ավարտել)։',
      },
    ],
  },
  {
    id: 'e2-s2',
    titleEs: '2. Busca el antónimo',
    titleHy: '2. Գտի՛ր հականիշը',
    questions: [
      {
        id: 'e2-q2',
        number: 2,
        category: 'antonimos',
        categoryLabelEs: 'Antónimo',
        categoryLabelHy: 'Հականիշ',
        promptEs: '¿Cuál es el antónimo de oscuro?',
        promptHy: 'Ո՞րն է oscuro բառի հականիշը։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. claro', textHy: 'լուսավոր / բաց' },
          { id: 'B', textEs: 'B. negro', textHy: 'սև' },
          { id: 'C', textEs: 'C. grande', textHy: 'մեծ' },
          { id: 'D', textEs: 'D. frío', textHy: 'սառը' },
        ],
        correctOptionId: 'A',
        correctAnswerEs: 'A. claro — լուսավոր',
        correctAnswerHy: 'A. claro — լուսավոր (oscuro ↔ claro)',
        explanationEs: 'Oscuro (con falta de luz) tiene como antónimo claro (con abundante luz).',
        explanationHy: '«oscuro» (մութ) բառի հականիշն է «claro» (լուսավոր, պարզ)։',
      },
    ],
  },
  {
    id: 'e2-s3',
    titleEs: '3. Sustituye por un sinónimo',
    titleHy: '3. Փոխարինի՛ր հոմանիշով',
    questions: [
      {
        id: 'e2-q3',
        number: 3,
        category: 'sinonimos',
        categoryLabelEs: 'Sustitución en frase',
        categoryLabelHy: 'Փոխարինում նախադասության մեջ',
        promptEs: 'El alumno contestó rápidamente.\n¿Qué palabra puede sustituir contestó?',
        promptHy: 'El alumno contestó rápidamente. (Աշակերտը արագ պատասխանեց։)\nՈ՞ր բառը կարող է փոխարինել contestó բառին։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. preguntó', textHy: 'հարցրեց' },
          { id: 'B', textEs: 'B. respondió', textHy: 'պատասխանեց' },
          { id: 'C', textEs: 'C. escribió', textHy: 'գրեց' },
          { id: 'D', textEs: 'D. escuchó', textHy: 'լսեց' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. respondió',
        correctAnswerHy: 'B. respondió (contestó = respondió — պատասխանեց)',
        explanationEs: 'Contestar y responder son verbos sinónimos. Preguntó es lo contrario.',
        explanationHy: '«contestó» = «respondió» (պատասխանեց)։ «preguntó» (հարցրեց) հակառակն է։',
      },
    ],
  },
  {
    id: 'e2-s4',
    titleEs: '4. Antónimos en contexto',
    titleHy: '4. Հականիշները համատեքստում',
    questions: [
      {
        id: 'e2-q4',
        number: 4,
        category: 'antonimos',
        categoryLabelEs: 'Antónimo en contexto',
        categoryLabelHy: 'Հականիշ համատեքստում',
        promptEs: 'La puerta estaba abierta.\nEscribe el antónimo de abierta.',
        promptHy: 'La puerta estaba abierta. (Դուռը բաց էր։)\nԳրի՛ր abierta բառի հականիշը։',
        type: 'open',
        correctAnswerEs: 'cerrada (La puerta estaba cerrada.)',
        correctAnswerHy: 'cerrada — փակ (Դուռը փակ էր։)',
        explanationEs: 'Abierta tiene como antónimo femenino cerrada.',
        explanationHy: '«abierta» (բաց) բառի հականիշն է «cerrada» (փակ)։',
      },
    ],
  },
  {
    id: 'e2-s-polisemia',
    titleEs: 'Polisemia',
    titleHy: 'Բազմիմաստություն',
    questions: [
      {
        id: 'e2-q5',
        number: 5,
        category: 'polisemia',
        categoryLabelEs: 'Polisemia',
        categoryLabelHy: 'Բազմիմաստություն',
        promptEs: 'Lee:\n"El gato está debajo de la mesa."\n"Necesitamos un gato para levantar el coche."\n¿Qué ocurre con gato?',
        promptHy: 'Կարդա՛.\n«Կատուն սեղանի տակ է։»\n«Մեզ պետք է gato մեքենան բարձրացնելու համար (դոմկրատ)։»\nԻ՞նչ է տեղի ունենում gato բառի հետ։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. Es un sinónimo.', textHy: 'Հոմանիշ է։' },
          { id: 'B', textEs: 'B. Es una palabra polisémica.', textHy: 'Բազմիմաստ բառ է։' },
          { id: 'C', textEs: 'C. Es un antónimo.', textHy: 'Հականիշ է։' },
          { id: 'D', textEs: 'D. Es un verbo.', textHy: 'Բայ է։' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. Palabra polisémica',
        correctAnswerHy: 'B. Palabra polisémica (Բազմիմաստ բառ)',
        explanationEs: 'Gato puede significar el animal felino y también la herramienta mecánica para elevar coches.',
        explanationHy: '«gato» կարող է նշանակել կատու (կենդանի), բայց նաև մեքենա բարձրացնելու գործիք (դոմկրատ)։',
      },
      {
        id: 'e2-q6',
        number: 6,
        category: 'polisemia',
        categoryLabelEs: 'Explicación polisemia',
        categoryLabelHy: 'Բազմիմաստության բացատրություն',
        promptEs: 'El jugador está en el banco.\nMi padre trabaja en un banco.\nExplica los dos significados de banco.',
        promptHy: 'El jugador está en el banco. (Խաղացողը պահեստայինների նստարանին է։)\nMi padre trabaja en un banco. (Հայրս բանկում է աշխատում։)\nԲացատրի՛ր banco բառի երկու իմաստները։',
        type: 'open',
        correctAnswerEs: 'banco = asiento / նստարան | banco = entidad financiera / բանկ ➡️ Polisemia',
        correctAnswerHy: 'banco = asiento (նստարան)\nbanco = entidad financiera (բանկ-դրամատուն)\n➡️ Polisemia — Բազմիմաստություն',
        explanationEs: 'Es un ejemplo clásico de polisemia: asiento largo y establecimiento financiero.',
        explanationHy: 'Միևնույն բառը տարբեր նախադասություններում նշանակում է նստարան և ֆինանսական հիմնարկ։',
      },
      {
        id: 'e2-q7',
        number: 7,
        category: 'polisemia',
        categoryLabelEs: 'Palabra polisémica',
        categoryLabelHy: 'Բազմիմաստ բառ',
        promptEs: 'La boca del niño.\nLa boca del túnel.\n¿Qué palabra es polisémica?',
        promptHy: 'La boca del niño. (Երեխայի բերանը։)\nLa boca del túnel. (Թունելի մուտքը։)\nՈ՞ր բառն է բազմիմաստ։',
        type: 'open',
        correctAnswerEs: 'boca',
        correctAnswerHy: 'boca (բերան / թունելի մուտք)',
        explanationEs: 'Boca designa tanto la parte anatómica de la cara como la abertura de entrada de un túnel o cueva.',
        explanationHy: '«boca» → բերան (մարդու), իսկ «boca del túnel» → թունելի մուտք։ Բազմիմաստ բառ է։',
      },
    ],
  },
  {
    id: 'e2-s-campo',
    titleEs: 'Campo semántico',
    titleHy: 'Իմաստային դաշտ',
    questions: [
      {
        id: 'e2-q8',
        number: 8,
        category: 'campo_semantico',
        categoryLabelEs: 'Identificar campo',
        categoryLabelHy: 'Իմաստային դաշտի որոշում',
        promptEs: 'lunes – martes – miércoles – jueves\n¿Cuál es el campo semántico de estas palabras?',
        promptHy: 'lunes – martes – miércoles – jueves (երկուշաբթի, երեքշաբթի, չորեքշաբթի, հինգշաբթի)\nՈ՞րն է այս բառերի իմաստային դաշտը։',
        type: 'open',
        correctAnswerEs: 'Días de la semana',
        correctAnswerHy: 'Շաբաթվա օրերի իմաստային դաշտ (Días de la semana)',
        explanationEs: 'Todas las palabras designan días de la semana y pertenecen a la misma categoría gramatical.',
        explanationHy: 'Բոլորը շաբաթվա օրեր են։',
      },
      {
        id: 'e2-q9',
        number: 9,
        category: 'campo_semantico',
        categoryLabelEs: 'Identificar campo',
        categoryLabelHy: 'Իմաստային դաշտի որոշում',
        promptEs: 'camisa – pantalones – chaqueta – falda\n¿A qué campo semántico pertenecen?',
        promptHy: 'camisa – pantalones – chaqueta – falda (վերնաշապիկ, տաբատ, բաճկոն, կիսաշրջազգեստ)\nՈ՞ր իմաստային դաշտին են պատկանում։',
        type: 'open',
        correctAnswerEs: 'La ropa / Prendas de vestir',
        correctAnswerHy: 'Հագուստ — La ropa / prendas de vestir',
        explanationEs: 'Todas son prendas de vestir que una persona puede llevar puestas.',
        explanationHy: 'Դրանք բոլորը հագուստի տեսակներ են։',
      },
      {
        id: 'e2-q10',
        number: 10,
        category: 'intruso',
        categoryLabelEs: 'Intruso',
        categoryLabelHy: 'Ավելորդ բառ',
        promptEs: 'Encuentra el intruso:\ntenedor – cuchillo – cuchara – zapato',
        promptHy: 'Գտի՛ր ավելորդ բառը.\ntenedor – cuchillo – cuchara – zapato (պատառաքաղ, դանակ, գդալ, կոշիկ)',
        type: 'open',
        correctAnswerEs: 'zapato',
        correctAnswerHy: 'zapato (կոշիկ, որովհետև մյուսները սեղանի պարագաներ / cubiertos են)։',
        explanationEs: 'Tenedor, cuchillo y cuchara son cubiertos de cocina. Zapato es calzado.',
        explanationHy: '«zapato» (կոշիկ) կոշկեղեն է, իսկ մյուսները սեղանի/խոհանոցային պարագաներ են։',
      },
      {
        id: 'e2-q11',
        number: 11,
        category: 'intruso',
        categoryLabelEs: 'Intruso',
        categoryLabelHy: 'Ավելորդ բառ',
        promptEs: 'Encuentra el intruso:\nportero – delantero – defensa – profesor',
        promptHy: 'Գտի՛ր ավելորդ բառը.\nportero – delantero – defensa – profesor (դարպասապահ, հարձակվող, պաշտպան, ուսուցիչ)',
        type: 'open',
        correctAnswerEs: 'profesor',
        correctAnswerHy: 'profesor (ուսուցիչ, որովհետև մյուս բառերը ֆուտբոլային դիրքեր են)։',
        explanationEs: 'Profesor es una profesión educativa; las demás son posiciones de jugadores de fútbol.',
        explanationHy: '«profesor»-ը մանկավարժ է, իսկ մյուսները ֆուտբոլային դաշտի դիրքեր են։',
      },
    ],
  },
  {
    id: 'e2-s-familia',
    titleEs: 'Familia léxica',
    titleHy: 'Բառակազմական ընտանիք',
    questions: [
      {
        id: 'e2-q12',
        number: 12,
        category: 'familia_lexica',
        categoryLabelEs: 'Familia léxica',
        categoryLabelHy: 'Բառակազմական ընտանիք',
        promptEs: '¿Cuál de estos grupos forma una familia léxica?',
        promptHy: 'Այս խմբերից ո՞րն է կազմում բառակազմական ընտանիք։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. casa – mesa – silla', textHy: 'տուն, սեղան, աթոռ' },
          { id: 'B', textEs: 'B. flor – florista – florero', textHy: 'ծաղիկ, ծաղկավաճառ, ծաղկաման' },
          { id: 'C', textEs: 'C. perro – gato – caballo', textHy: 'շուն, կատու, ձի' },
          { id: 'D', textEs: 'D. rojo – verde – azul', textHy: 'կարմիր, կանաչ, կապույտ' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. flor – florista – florero',
        correctAnswerHy: 'B. flor – florista – florero (նույն արմատն ունեն՝ flor-)։',
        explanationEs: 'Tienen la misma raíz morfológica flor-. Las demás opciones son campos semánticos.',
        explanationHy: 'Բոլոր երեք բառերը կազմված են «flor-» արմատից։',
      },
      {
        id: 'e2-q13',
        number: 13,
        category: 'intruso',
        categoryLabelEs: 'Intruso en la familia',
        categoryLabelHy: 'Ավելորդ բառ ընտանիքում',
        promptEs: 'Busca la palabra que NO pertenece a la familia léxica de mar:\nmarino – marinero – marítimo – naranja',
        promptHy: 'Գտի՛ր այն բառը, որը ՉԻ պատկանում mar բառի ընտանիքին.\nmarino – marinero – marítimo – naranja',
        type: 'open',
        correctAnswerEs: 'naranja',
        correctAnswerHy: 'naranja (նարինջ, չունի mar- արմատը)',
        explanationEs: 'Naranja es una fruta y carece de la raíz mar-.',
        explanationHy: '«naranja» (նարինջ) բառը չունի mar- արմատը։',
      },
      {
        id: 'e2-q14',
        number: 14,
        category: 'familia_lexica',
        categoryLabelEs: 'Completa la familia',
        categoryLabelHy: 'Լրացրո՛ւ ընտանիքը',
        promptEs: 'Completa:\npan → panadero → panadería → ______',
        promptHy: 'Լրացրո՛ւ.\npan → panadero → panadería → ______',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. zapatero', textHy: 'կոշկակար' },
          { id: 'B', textEs: 'B. panecillo', textHy: 'փոքր հացիկ, բուլկի' },
          { id: 'C', textEs: 'C. pescador', textHy: 'ձկնորս' },
          { id: 'D', textEs: 'D. frutero', textHy: 'մրգավաճառ' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. panecillo',
        correctAnswerHy: 'B. panecillo (բոլորն ունեն pan- արմատը)։',
        explanationEs: 'Panecillo mantiene la raíz pan-. Los otros términos derivan de zapato, pescado y fruta.',
        explanationHy: '«panecillo»-ն (փոքր հաց) նույնպես առաջացել է pan արմատից։',
      },
    ],
  },
  {
    id: 'e2-s-contexto',
    titleEs: 'Significado según el contexto',
    titleHy: 'Իմաստը ըստ համատեքստի',
    questions: [
      {
        id: 'e2-q15',
        number: 15,
        category: 'contexto',
        categoryLabelEs: 'Contexto',
        categoryLabelHy: 'Համատեքստ',
        promptEs: 'El examen fue muy duro.\n¿Qué significa duro aquí?',
        promptHy: 'El examen fue muy duro. (Քննությունը շատ duro էր։)\nԻ՞նչ է նշանակում duro այստեղ։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. difícil', textHy: 'դժվար, բարդ' },
          { id: 'B', textEs: 'B. blando', textHy: 'փափուկ' },
          { id: 'C', textEs: 'C. rápido', textHy: 'արագ' },
          { id: 'D', textEs: 'D. pequeño', textHy: 'փոքր' },
        ],
        correctOptionId: 'A',
        correctAnswerEs: 'A. difícil',
        correctAnswerHy: 'A. difícil (Այստեղ «duro» նշանակում է «դժվար»)։',
        explanationEs: 'Duro en el contexto de una prueba o examen significa riguroso o difícil.',
        explanationHy: 'Քննության կամ փորձության համատեքստում «duro» նշանակում է բարդ, դժվար։',
      },
      {
        id: 'e2-q16',
        number: 16,
        category: 'contexto',
        categoryLabelEs: 'Expresión figurada',
        categoryLabelHy: 'Փոխաբերական արտահայտություն',
        promptEs: 'El entrenador dio luz verde al jugador para volver al campo.\n¿Qué significa dar luz verde?',
        promptHy: 'El entrenador dio luz verde al jugador para volver al campo.\nԻ՞նչ է նշանակում «dar luz verde» այստեղ։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. encender una lámpara', textHy: 'լամպ վառել' },
          { id: 'B', textEs: 'B. dar permiso', textHy: 'թույլտվություն տալ' },
          { id: 'C', textEs: 'C. parar el partido', textHy: 'դադարեցնել խաղը' },
          { id: 'D', textEs: 'D. cambiar de equipo', textHy: 'թիմը փոխել' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. dar permiso — թույլտվություն տալ',
        correctAnswerHy: 'B. dar permiso — թույլտվություն տալ («կանաչ լույս վառել»)',
        explanationEs: '"Dar luz verde" es una expresión idiomática que significa autorizar o permitir una acción.',
        explanationHy: '«Կանաչ լույս վառել» նշանակում է թույլատրել, համաձայնություն տալ։',
      },
      {
        id: 'e2-q17',
        number: 17,
        category: 'contexto',
        categoryLabelEs: 'Modismo',
        categoryLabelHy: 'Դարձվածք',
        promptEs: 'Pedro tiene la cabeza en las nubes.\n¿Qué significa?',
        promptHy: 'Pedro tiene la cabeza en las nubes. (Պեդրոյի գլուխը ամպերում է։)\nԻ՞նչ է նշանակում այս արտահայտությունը։',
        type: 'choice',
        options: [
          { id: 'A', textEs: 'A. Es muy alto.', textHy: 'Շատ բարձրահասակ է։' },
          { id: 'B', textEs: 'B. Está distraído.', textHy: 'Ցրված է, ուշադիր չէ։' },
          { id: 'C', textEs: 'C. Tiene dolor de cabeza.', textHy: 'Գլխացավ ունի։' },
          { id: 'D', textEs: 'D. Está enfadado.', textHy: 'Բարկացած է։' },
        ],
        correctOptionId: 'B',
        correctAnswerEs: 'B. Está distraído.',
        correctAnswerHy: 'B. Está distraído (Գլուխը ամպերում է → ցրված է, անուշադիր)։',
        explanationEs: '"Tener la cabeza en las nubes" alude a una persona soñadora o poco atenta a la realidad.',
        explanationHy: 'Նշանակում է մտքերով հեռու լինել, ցրված կամ անուշադիր լինել։',
      },
    ],
  },
  {
    id: 'e2-s-sentido',
    titleEs: 'Sentido literal y figurado',
    titleHy: 'Ուղիղ և փոխաբերական իմաստ',
    questions: [
      {
        id: 'e2-q18',
        number: 18,
        category: 'figurado',
        categoryLabelEs: 'Literal o figurado',
        categoryLabelHy: 'Ուղիղ, թե փոխաբերական',
        promptEs: 'El niño tiene las manos frías.\n¿Sentido literal o figurado?',
        promptHy: 'El niño tiene las manos frías. (Երեխայի ձեռքերը սառն են։)\nՈւղի՞ղ, թե՞ փոխաբերական իմաստ։',
        type: 'choice',
        options: [
          { id: 'L', textEs: 'Sentido literal', textHy: 'Ուղիղ իմաստ' },
          { id: 'F', textEs: 'Sentido figurado', textHy: 'Փոխաբերական իմաստ' },
        ],
        correctOptionId: 'L',
        correctAnswerEs: 'Sentido literal — Ուղիղ իմաստ',
        correctAnswerHy: 'Sentido literal — Ուղիղ իմաստ (Նրա ձեռքերը իսկապես սառն են)։',
        explanationEs: 'Describe una realidad física y comprobable: la baja temperatura de sus manos.',
        explanationHy: 'Բառերն օգտագործված են իրենց բուն իմաստով (ձեռքերի իրական ջերմաստիճանը ցածր է)։',
      },
      {
        id: 'e2-q19',
        number: 19,
        category: 'figurado',
        categoryLabelEs: 'Literal o figurado',
        categoryLabelHy: 'Ուղիղ, թե փոխաբերական',
        promptEs: 'Carlos es un león en el campo.\n¿Sentido literal o figurado?',
        promptHy: 'Carlos es un león en el campo. (Կառլոսը դաշտում առյուծ է։)\nՈւղի՞ղ, թե՞ փոխաբերական իմաստ։',
        type: 'choice',
        options: [
          { id: 'L', textEs: 'Sentido literal', textHy: 'Ուղիղ իմաստ' },
          { id: 'F', textEs: 'Sentido figurado', textHy: 'Փոխաբերական իմաստ' },
        ],
        correctOptionId: 'F',
        correctAnswerEs: 'Sentido figurado — Փոխաբերական իմաստ',
        correctAnswerHy: 'Sentido figurado — Փոխաբերական իմաստ (Կառլոսը կենդանի առյուծ չէ, այլ շատ ուժեղ ու համարձակ է)։',
        explanationEs: 'Carlos no es un animal, sino que se compara su valentía y fuerza con las de un león.',
        explanationHy: 'Կառլոսը իրական առյուծ չէ. սա փոխաբերություն է՝ նշելու նրա քաջությունն ու ուժը։',
      },
      {
        id: 'e2-q20',
        number: 20,
        category: 'figurado',
        categoryLabelEs: 'Literal o figurado',
        categoryLabelHy: 'Ուղիղ, թե փոխաբերական',
        promptEs: 'Ese examen fue un infierno.\n¿Sentido literal o figurado?',
        promptHy: 'Ese examen fue un infierno. (Այդ քննությունը դժոխք էր։)\nՈւղի՞ղ, թե՞ փոխաբերական իմաստ։',
        type: 'choice',
        options: [
          { id: 'L', textEs: 'Sentido literal', textHy: 'Ուղիղ իմաստ' },
          { id: 'F', textEs: 'Sentido figurado', textHy: 'Փոխաբերական իմաստ' },
        ],
        correctOptionId: 'F',
        correctAnswerEs: 'Sentido figurado',
        correctAnswerHy: 'Sentido figurado (Նշանակում է՝ քննությունը շատ դժվար կամ տհաճ էր)։',
        explanationEs: 'Se exagera diciendo que fue un infierno para enfatizar su extrema dificultad.',
        explanationHy: 'Քննությունը բառացիորեն դժոխք չէ, այլ շատ ծանր, տանջալից կամ դժվար էր։',
      },
    ],
  },
  {
    id: 'e2-s-sinonimos-comp',
    titleEs: 'Completa con sinónimos',
    titleHy: 'Լրացրո՛ւ հոմանիշներով',
    questions: [
      {
        id: 'e2-q21',
        number: 21,
        category: 'sinonimos',
        categoryLabelEs: 'Sustituye sinónimo',
        categoryLabelHy: 'Հոմանիշի փոխարինում',
        promptEs: 'El partido fue muy emocionante.\nSustituye emocionante por un sinónimo.',
        promptHy: 'El partido fue muy emocionante. (Խաղը շատ հուզիչ/ոգևորիչ էր։)\nՓոխարինի՛ր emocionante բառը հոմանիշով։',
        type: 'open',
        correctAnswerEs: 'interesante / apasionante',
        correctAnswerHy: 'interesante (հետաքրքիր) կամ apasionante (կրքոտ, ոգևորիչ)',
        explanationEs: 'Apasionante e interesante transmiten la misma emoción que provocó el partido.',
        explanationHy: '«emocionante» բառի հոմանիշներն են «apasionante» կամ «interesante»։',
      },
      {
        id: 'e2-q22',
        number: 22,
        category: 'sinonimos',
        categoryLabelEs: 'Sustituye sinónimo',
        categoryLabelHy: 'Հոմանիշի փոխարինում',
        promptEs: 'El entrenador estaba enfadado.\nSustituye enfadado por un sinónimo.',
        promptHy: 'El entrenador estaba enfadado. (Մարզիչը զայրացած էր։)\nՓոխարինի՛ր enfadado բառը հոմանիշով։',
        type: 'open',
        correctAnswerEs: 'molesto / enojado',
        correctAnswerHy: 'molesto (դժգոհ, նեղված) կամ enojado (զայրացած)',
        explanationEs: 'Enfadado tiene como sinónimos molesto, disgustado o enojado.',
        explanationHy: '«enfadado» բառի հոմանիշներն են «molesto» կամ «enojado»։',
      },
    ],
  },
  {
    id: 'e2-s-antonimos-comp',
    titleEs: 'Completa con antónimos',
    titleHy: 'Լրացրո՛ւ հականիշներով',
    questions: [
      {
        id: 'e2-q23',
        number: 23,
        category: 'antonimos',
        categoryLabelEs: 'Completa antónimo',
        categoryLabelHy: 'Հականիշով լրացում',
        promptEs: 'El delantero es rápido, pero el defensa es ______.\n(Completa con el antónimo de rápido)',
        promptHy: 'El delantero es rápido, pero el defensa es ______.\n(Լրացրո՛ւ rápido բառի հականիշով)',
        type: 'open',
        correctAnswerEs: 'lento',
        correctAnswerHy: 'lento — դանդաղ (Հարձակվողը արագ է, իսկ պաշտպանը՝ դանդաղ)։',
        explanationEs: 'El antónimo directo de rápido es lento.',
        explanationHy: '«rápido» (արագ) ↔ «lento» (դանդաղ)։',
      },
      {
        id: 'e2-q24',
        number: 24,
        category: 'antonimos',
        categoryLabelEs: 'Completa antónimo',
        categoryLabelHy: 'Հականիշով լրացում',
        promptEs: 'Antes el estadio estaba vacío, pero ahora está ______.\n(Completa con el antónimo de vacío)',
        promptHy: 'Antes el estadio estaba vacío, pero ahora está ______.\n(Լրացրո՛ւ vacío բառի հականիշով)',
        type: 'open',
        correctAnswerEs: 'lleno',
        correctAnswerHy: 'lleno — լիքը (Նախկինում մարզադաշտը դատարկ էր, իսկ հիմա՝ լիքը)։',
        explanationEs: 'El antónimo de vacío es lleno.',
        explanationHy: '«vacío» (դատարկ) ↔ «lleno» (լիքը, լեցուն)։',
      },
    ],
  },
  {
    id: 'e2-s-texto2',
    titleEs: 'Lee y analiza (Texto 2)',
    titleHy: 'Կարդա՛ և վերլուծի՛ր (Տեքստ 2)',
    subtitleEs: 'Comprensión del partido de Carlos',
    subtitleHy: 'Կառլոսի խաղի մասին տեքստի վերլուծություն',
    textEs: 'El sábado Carlos jugó un partido muy difícil. Su equipo empezó perdiendo, pero consiguió empatar en la segunda parte. Carlos estaba muy cansado, aunque siguió corriendo hasta el final. Después del partido, el entrenador estaba contento con todos los jugadores.',
    textHy: 'Շաբաթ օրը Կառլոսը շատ դժվար խաղ խաղաց։ Նրա թիմը սկզբում պարտվում էր, բայց երկրորդ խաղակեսում կարողացավ հավասարեցնել հաշիվը։ Կառլոսը շատ հոգնած էր, սակայն շարունակեց վազել մինչև վերջ։ Խաղից հետո մարզիչը գոհ էր բոլոր խաղացողներից։',
    questions: [
      {
        id: 'e2-q25',
        number: 25,
        category: 'texto',
        categoryLabelEs: 'Texto 2',
        categoryLabelHy: 'Տեքստ 2',
        promptEs: 'Busca en el texto o escribe un sinónimo de contento.',
        promptHy: 'Տեքստի հիման վրա գրի՛ր contento բառի հոմանիշը։',
        type: 'open',
        correctAnswerEs: 'feliz / satisfecho',
        correctAnswerHy: 'feliz / satisfecho (ուրախ / գոհ)',
        explanationEs: 'El entrenador estaba satisfecho o feliz con el rendimiento del equipo.',
        explanationHy: 'Մարզիչը գոհ կամ ուրախ էր խաղացողներից։',
      },
      {
        id: 'e2-q26',
        number: 26,
        category: 'texto',
        categoryLabelEs: 'Texto 2',
        categoryLabelHy: 'Տեքստ 2',
        promptEs: 'Escribe el antónimo de difícil que contrasta con el partido de Carlos.',
        promptHy: 'Գրի՛ր difícil բառի հականիշը։',
        type: 'open',
        correctAnswerEs: 'fácil',
        correctAnswerHy: 'fácil — հեշտ',
        explanationEs: 'El antónimo de difícil es fácil.',
        explanationHy: '«difícil» (դժվար) բառի հականիշն է «fácil» (հեշտ)։',
      },
      {
        id: 'e2-q27',
        number: 27,
        category: 'texto',
        categoryLabelEs: 'Texto 2',
        categoryLabelHy: 'Տեքստ 2',
        promptEs: 'Escribe el antónimo de empezar.',
        promptHy: 'Գրի՛ր empezar բառի հականիշը։',
        type: 'open',
        correctAnswerEs: 'terminar / acabar',
        correctAnswerHy: 'terminar / acabar — ավարտել',
        explanationEs: 'Empezar se opone a terminar o acabar.',
        explanationHy: '«empezar» (սկսել) բառի հականիշներն են «terminar» կամ «acabar» (ավարտել)։',
      },
      {
        id: 'e2-q28',
        number: 28,
        category: 'texto',
        categoryLabelEs: 'Texto 2',
        categoryLabelHy: 'Տեքստ 2',
        promptEs: 'Busca dos palabras en el texto del campo semántico del fútbol.',
        promptHy: 'Տեքստում գտի՛ր ֆուտբոլի իմաստային դաշտին պատկանող երկու բառ։',
        type: 'open',
        correctAnswerEs: 'partido / equipo / entrenador / jugadores',
        correctAnswerHy: 'partido (խաղ), equipo (թիմ), entrenador (մարզիչ), jugadores (խաղացողներ)',
        explanationEs: 'Cualquiera de estas palabras pertenece al campo semántico del fútbol.',
        explanationHy: 'Տեքստում առկա բոլոր այս բառերը պատկանում են ֆուտբոլի իմաստային դաշտին։',
      },
    ],
  },
  {
    id: 'e2-s-preguntas-tipicas',
    titleEs: 'Preguntas típicas de examen',
    titleHy: 'Քննության տիպիկ հարցեր',
    subtitleEs: 'Preguntas de desarrollo conceptual y clasificación total',
    subtitleHy: 'Տեսական սահմանումներ և ընդհանուր դասակարգում',
    questions: [
      {
        id: 'e2-q29',
        number: 29,
        category: 'clasificacion',
        categoryLabelEs: 'Teoría de examen',
        categoryLabelHy: 'Քննության տեսություն',
        promptEs: '¿Qué diferencia hay entre campo semántico y familia léxica?',
        promptHy: 'Ի՞նչ տարբերություն կա «իմաստային դաշտի» (campo semántico) և «բառակազմական ընտանիքի» (familia léxica) միջև։',
        type: 'open',
        correctAnswerEs: 'Un campo semántico reúne palabras relacionadas por su significado; una familia léxica reúne palabras que comparten la misma raíz.',
        correctAnswerHy: 'Իմաստային դաշտը միավորում է նույն թեմայի բառերը (արմատները կարող են տարբեր լինել), իսկ բառակազմական ընտանիքը՝ նույն արմատն ունեցող բառերը։',
        explanationEs: 'Ejemplo: fútbol – tenis – baloncesto → campo semántico | pan – panadero – panadería → familia léxica.',
        explanationHy: 'Օրինակ՝ fútbol – tenis – baloncesto → իմաստային դաշտ | pan – panadero – panadería → բառակազմական ընտանիք։',
      },
      {
        id: 'e2-q30a',
        number: '30.a',
        category: 'clasificacion',
        categoryLabelEs: 'Clasifica',
        categoryLabelHy: 'Դասակարգի՛ր',
        promptEs: 'Clasifica: alegre / feliz',
        promptHy: 'Դասակարգի՛ր. alegre / feliz',
        type: 'choice',
        options: [
          { id: 'sin', textEs: 'Sinonimia', textHy: 'Հոմանիշներ' },
          { id: 'ant', textEs: 'Antonimia', textHy: 'Հականիշներ' },
          { id: 'pol', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'cam', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'fam', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
          { id: 'fig', textEs: 'Sentido figurado', textHy: 'Փոխաբերական իմաստ' },
        ],
        correctOptionId: 'sin',
        correctAnswerEs: 'Sinonimia (Հոմանիշներ)',
        correctAnswerHy: 'Հոմանիշներ (երկուսն էլ նշանակում են ուրախ)',
      },
      {
        id: 'e2-q30b',
        number: '30.b',
        category: 'clasificacion',
        categoryLabelEs: 'Clasifica',
        categoryLabelHy: 'Դասակարգի՛ր',
        promptEs: 'Clasifica: frío / caliente',
        promptHy: 'Դասակարգի՛ր. frío / caliente',
        type: 'choice',
        options: [
          { id: 'sin', textEs: 'Sinonimia', textHy: 'Հոմանիշներ' },
          { id: 'ant', textEs: 'Antonimia', textHy: 'Հականիշներ' },
          { id: 'pol', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'cam', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'fam', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
          { id: 'fig', textEs: 'Sentido figurado', textHy: 'Փոխաբերական իմաստ' },
        ],
        correctOptionId: 'ant',
        correctAnswerEs: 'Antonimia (Հականիշներ)',
        correctAnswerHy: 'Հականիշներ (սառը ↔ տաք)',
      },
      {
        id: 'e2-q30c',
        number: '30.c',
        category: 'clasificacion',
        categoryLabelEs: 'Clasifica',
        categoryLabelHy: 'Դասակարգի՛ր',
        promptEs: 'Clasifica: banco: asiento / entidad financiera',
        promptHy: 'Դասակարգի՛ր. banco: asiento / entidad financiera',
        type: 'choice',
        options: [
          { id: 'sin', textEs: 'Sinonimia', textHy: 'Հոմանիշներ' },
          { id: 'ant', textEs: 'Antonimia', textHy: 'Հականիշներ' },
          { id: 'pol', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'cam', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'fam', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
          { id: 'fig', textEs: 'Sentido figurado', textHy: 'Փոխաբերական իմաստ' },
        ],
        correctOptionId: 'pol',
        correctAnswerEs: 'Polisemia (Բազմիմաստություն)',
        correctAnswerHy: 'Բազմիմաստություն (միևնույն բառը մի քանի իմաստ ունի)',
      },
      {
        id: 'e2-q30d',
        number: '30.d',
        category: 'clasificacion',
        categoryLabelEs: 'Clasifica',
        categoryLabelHy: 'Դասակարգի՛ր',
        promptEs: 'Clasifica: camisa / falda / pantalones',
        promptHy: 'Դասակարգի՛ր. camisa / falda / pantalones',
        type: 'choice',
        options: [
          { id: 'sin', textEs: 'Sinonimia', textHy: 'Հոմանիշներ' },
          { id: 'ant', textEs: 'Antonimia', textHy: 'Հականիշներ' },
          { id: 'pol', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'cam', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'fam', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
          { id: 'fig', textEs: 'Sentido figurado', textHy: 'Փոխաբերական իմաստ' },
        ],
        correctOptionId: 'cam',
        correctAnswerEs: 'Campo semántico (Իմաստային դաշտ)',
        correctAnswerHy: 'Իմաստային դաշտ (հագուստի թեման է, տարբեր արմատներով)',
      },
      {
        id: 'e2-q30e',
        number: '30.e',
        category: 'clasificacion',
        categoryLabelEs: 'Clasifica',
        categoryLabelHy: 'Դասակարգի՛ր',
        promptEs: 'Clasifica: flor / florista / florero',
        promptHy: 'Դասակարգի՛ր. flor / florista / florero',
        type: 'choice',
        options: [
          { id: 'sin', textEs: 'Sinonimia', textHy: 'Հոմանիշներ' },
          { id: 'ant', textEs: 'Antonimia', textHy: 'Հականիշներ' },
          { id: 'pol', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'cam', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'fam', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
          { id: 'fig', textEs: 'Sentido figurado', textHy: 'Փոխաբերական իմաստ' },
        ],
        correctOptionId: 'fam',
        correctAnswerEs: 'Familia léxica (Բառակազմական ընտանիք)',
        correctAnswerHy: 'Բառակազմական ընտանիք (բոլորն ունեն flor- արմատը)',
      },
      {
        id: 'e2-q30f',
        number: '30.f',
        category: 'clasificacion',
        categoryLabelEs: 'Clasifica',
        categoryLabelHy: 'Դասակարգի՛ր',
        promptEs: 'Clasifica: "Carlos es un león jugando al fútbol."',
        promptHy: 'Դասակարգի՛ր. «Carlos es un león jugando al fútbol.»',
        type: 'choice',
        options: [
          { id: 'sin', textEs: 'Sinonimia', textHy: 'Հոմանիշներ' },
          { id: 'ant', textEs: 'Antonimia', textHy: 'Հականիշներ' },
          { id: 'pol', textEs: 'Polisemia', textHy: 'Բազմիմաստություն' },
          { id: 'cam', textEs: 'Campo semántico', textHy: 'Իմաստային դաշտ' },
          { id: 'fam', textEs: 'Familia léxica', textHy: 'Բառակազմական ընտանիք' },
          { id: 'fig', textEs: 'Sentido figurado', textHy: 'Փոխաբերական իմաստ' },
        ],
        correctOptionId: 'fig',
        correctAnswerEs: 'Sentido figurado (Փոխաբերական իմաստ)',
        correctAnswerHy: 'Փոխաբերական իմաստ (նա իսկական առյուծ չէ, այլ ուժեղ և քաջ է)',
      },
    ],
  },
];
